#!/bin/bash
echo "=== Quick Diagnostic Check ==="
echo ""
echo "1. Dev Server Status:"
curl -s http://localhost:5174 | grep -o "<div id=\"root\"></div>" && echo "✅ HTML root div exists" || echo "❌ No root div found"
echo ""
echo "2. Main script loading:"
curl -s http://localhost:5174 | grep -o "src=\"/src/main.tsx\"" && echo "✅ Main script tag exists" || echo "❌ No main script"
echo ""
echo "3. React should mount here. If you see blank page:"
echo "   - Open browser DevTools (F12 or Cmd+Option+I)"
echo "   - Go to Console tab"
echo "   - Look for red errors"
echo "   - Share what errors you see"
